#!/bin/sh

# Exit on error, undefined variables, and pipe failures
set -euo pipefail

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  # setup macos defaults
  if [ -f "$HOME/.macos" ]; then
    echo "Setting macOS defaults"
    . "$HOME/.macos"
  fi

  echo "Installing iterm2 themes"
  open .config/iterm2/GitHub\ Dark\ Dimmed.itermcolors
  open .config/iterm2/GitHub\ Light\ Default.itermcolors
fi

# install volta if it's missing
if ! command -v volta >/dev/null 2>&1; then
  echo "Installing Volta (Node Version Manager)"
  # Install Volta
  curl https://get.volta.sh | bash

  # Load volta
  export VOLTA_HOME="$HOME/.volta"
  export PATH="$VOLTA_HOME/bin:$PATH"

  # Install latest LTS Node.js
  volta install node
fi
