#!/bin/sh

# Exit on error, undefined variables, and pipe failures
set -euo pipefail

# install homebrew if it's missing
if ! command -v brew >/dev/null 2>&1; then
  echo "Installing homebrew"
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

if [ -f "$HOME/Brewfile" ]; then
  echo "Updating homebrew bundle"
  brew bundle --global
fi

SYSTEM_TYPE=$(uname -s)

if [ "$SYSTEM_TYPE" = "Darwin" ]; then
  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  # setup macos defaults
  if [ -f "$HOME/.macos" ]; then
    echo "Setting macOS defaults"
    . "$HOME/.macos"
  fi

  echo "Installing iterm2 themes"
  open .config/iterm2/GitHub\ Dark\ Dimmed.itermcolors
  open .config/iterm2/GitHub\ Light\ Default.itermcolors
fi


if [ -x command -v volta ]; then
  echo "Installing latest LTS Node.js via Volta"
  volta install node
fi

if [ "$SHELL" != "$(which zsh)" ]; then
  echo "Changing default shell to zsh"
  chsh -s $(which zsh)
fi
